name: Appointment Checker

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  
  # Allows manual triggering for testing
  workflow_dispatch:

jobs:
  check-appointments:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run appointment checker
      run: python appointment_checker.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        
    - name: Log completion
      run: echo "✅ Appointment check completed at $(date)"