name: Appointment Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Chrome and Chromedriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install selenium requests

      - name: Run appointment checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python appointment_checker.py